### ISSUE TITLE
Create templated type for return value

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [mweststrate/use-st8#7]
Thanks for this library, it's really nifty!

I'd like to represent an object containing st8 values _(is that the right nomenclature?)_, but `ReturnType<typeof useSt8>` isn't syntactically allowed to include a `<T>` generic value.

```ts
type St8Number= ReturnType<typeof useSt8<number>>;
// '>' expected.ts(1005)
```

I'd be happy to send a PR that splits out a standalone type returned by `useSt8`:

```ts
export type St8<T> = {
    (): T;
    (newValue: T | ((current: T) => T)): void;
};

export default function useSt8<T>(i: (() => T) | T): St8<T>;
```

**Comment by mweststrate** [comment]
Feel free to open a PR :)
